stages:
  - build
  - test

image: maven:3.9.6-amazoncorretto-21 # Das ist das Image, das für alle Jobs verwendet wwerden soll

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository" # das ist der Pfad wo das Maven Repository gespeichert wird, eine Globale enviroment variable die für alle Jobs gilt

build: # Das ist der name des Jobs und jeder job gehört zu einem Stage (bspw wenn build nur für win dann build-win)
  stage: build
  tags:
    - docker
  script:
    - mvn compile
  artifacts: # sind ergebnisse eines jobs die an andere jobs weitergegeben werden (WICHTIG! funktioniert bei uns auch ohne aber nur weil wir einen runner haben)
    paths:
      - "target/*" # target ist der standard output ordner von maven
    expire_in: 2 days # wie lange die artifacts aufbewahrt werden sollen
  cache:
    paths:
      - ".m2/repository" # Maven Repository wird gecached somit muss nicht jedes mal alles neu heruntergeladen werden

# leere Zeile ist notwendig um die Jobs zu trennen

test:
  stage: build
  tags:
    - docker
  dependencies:
    - build # das bedeutet das dieser Job auf die artifacts des build Jobs zugreift
  script:
    - mvn test
  cache:
    paths:
      - ".m2/repository"

