stages:
  - build
  - test

image: maven:3.9.6-amazoncorretto-21 # Das ist das Image, das für alle Jobs verwendet wwerden soll

build: # Das ist der name des Jobs und jeder job gehört zu einem Stage (bspw wenn build nur für win dann build-win)
  stage: build
  tags:
    - docker
  script:
    - mvn compile

# leere Zeile ist notwendig um die Jobs zu trennen

